#!/bin/bash

function today () {
  # Load user preferences
  [ -f ~/.todayrc ] && . ~/.todayrc

  # defaults
  TODAYROOT=${TODAYROOT:-~/today}
  DATEFORMAT=${DATEFORMAT:-%Y-%m-%d}
  NOTESUFFIX=${NOTESUFFIX:-.md}

  export TODAYDIR="$TODAYROOT"/`date +"$DATEFORMAT"`
  mkdir -p "$TODAYDIR"

  case $1 in
    cd|dir)
      cd "$TODAYDIR"
      ;;
    help)
cat << EOF
Usage:
  today
    Create today directory and nothing else
  today cd
    Change directory to today's directory (only works when sourced as function)
  today note
    Write or amend today's notes.
EOF
      ;;
    notes|note)
      NOTEFILE="${TODAYDIR}/notes${NOTESUFFIX}"
      "${EDITOR:-vim}" "$NOTEFILE"
      RETVAL=$?
      if [ $RETVAL -ne 0 ]; then
        echo "Failed to write note file (${NOTEFILE}): exit code ${RETVAL}" >&2
      else
        echo "$NOTEFILE"
      fi
      return $RETVAL
      ;;
    *)
      echo "$TODAYDIR"
      ;;
  esac
}

case $(basename -- $0) in
  today)
    today "$@"
    exit $?
    ;;
  today-*)
    today ${0##*today-} "$@"
    exit $?
    ;;
  *)
    #sourced, do nothing
    ;;
esac
